### ISSUE TITLE
Review identifier list

### ISSUE THREAD

**Issue by physikerwelt** [physikerwelt/texvcinfo#2]
@howardcohl: Can you have a look at 

https://github.com/physikerwelt/texvcTokens/blob/master/doc/main.tex

https://github.com/physikerwelt/texvcTokens/blob/master/doc/literals.tex

https://github.com/physikerwelt/texvcTokens/blob/master/doc/commands.tex

and see if that makes sense to you. I'm not sure if we should remove some commands from the literals list.

**Comment by HowardCohl** [comment]
I'm looking at it now.

Yes it makes sense. But I'm not sure what you are getting at.

Why does \mathcal{x} produce the same as \S ? 
I understand that mathcal is not available for lower case letters, but why does it choose the \S symbol?

**Comment by physikerwelt** [comment]
We should consider to also extract operators.
i.e. \operatorname is always an opertor.
